### ISSUE TITLE
Upload de pdf para assinar (freelancer)

### ISSUE THREAD

**Issue by hermesalvesbr** [ZaunSupremoXV/pdf_sign#1]
Olá,

Eu preciso de um projeto nuxt3 simples para assinar o arquivo pdf no rodapé usando o certificado digital p12. Eu vi que você já trabalhou com  pdfsign: https://github.com/vbuch/node-signpdf/issues/28 

Funcionalidades que preciso:
1 - Selecionar arquivo pdf
2 - Selecionar certificado digital
3 - Inserir senha do certificado digital
4 - Baixar o pdf (1) assinado no rodapé.

Tem interesse neste projeto?

**Comment by hermesalvesbr** [comment]
https://assina.ufsc.br/verificador/

**Comment by ZaunSupremoXV** [comment]
Olá Hermes Alves. Tenho interesse sim. Desculpe pela demora.

Em qui., 24 de mar. de 2022 às 19:24, Hermes Alves ***@***.***>
escreveu:

**Comment by ZaunSupremoXV** [comment]
Olá Hermes Alves. Tenho interesse sim. Desculpe pela demora.

**Comment by ZaunSupremoXV** [comment]
Você pode entrar em contato comigo no e-mail erick_vasconcelos_contato@outlook.com

**Comment by hermesalvesbr** [comment]
Bom dia,

Te enviei e-mail de hermes.alves@araripina.com.br. Poderia excluir essa issue?
